### ISSUE TITLE
the Speaker List segment

### ISSUE THREAD

**Issue by mapconcierge** [sotm-asia/sotm-asia-2023-website#1]
https://stateofthemap.asia/

<img width="1512" alt="スクリーンショット 2023-08-20 11 07 00" src="https://github.com/sotm-asia/sotm-asia-2023-website/assets/416977/e92187c7-fc38-4641-84c6-328274302f14">

# Abstract

State of the Map Asia gathers mappers from diverse nations to share the current mapping status of their respective countries and introduce various projects they are involved in. The Talk session serves as a platform for these mappers to engage in lively discussions, exchange ideas, and collaborate on mapping challenges. It not only fosters a sense of community among OpenStreetMap enthusiasts but also promotes the growth and development of open-source mapping in the Asian region.

**Comment by mapconcierge** [comment]
# Nama

Dr. Nama, the inaugural Regional Director of the Open Mapping Hub – Asia Pacific for HOT, has a diverse background spanning government, non-profit, academia, and start-ups. He founded Kathmandu Living Labs, gaining recognition in major media outlets and was awarded as an impactful social innovator in 2018. Previously, he led the World Bank’s Open Cities project in Nepal. Holding a doctorate focused on OpenStreetMap from the University of Illinois, he has authored numerous publications and served as an IT officer for the Nepalese government.

**Comment by mapconcierge** [comment]
# Taichi

Prof. Taichi is passionate about mapping, connecting local communities with maps and sharing knowledge to empower people. As you know, Huge Earthquake and Tsunami destroyed a lot of cities and local communities in East Japan area, 2011. He and local people are trying, how to make more resilient society with Mapping, Panorama/VR and Drone technology. Taichi is a professor of Aoyama Gakuin University and President of CrisisMappers Japan, NPO. Now he has started DRONEBIRD project with drones for Disaster Crisis Response. In addition, he has worked for advisory board chairman of Project PLATEAU.

**Comment by mapconcierge** [comment]
# Mikko

Mikko is the Community Manager for Asia at HOT. He has been actively contributing on OpenStreetMap since 2014 and has worked as a volunteer mapper with several non-governmental organizations such as UN Human Settlements Programme, Philippine Red Cross, Cordaid, and the Asia Foundation. Mikko is also the founder of MapBeks - an online community of mappers advocating for LGBT representation and inclusion on OSM.

**Comment by bdmapman** [comment]
Done!!!
